### ISSUE TITLE
kmltrack AIS positions colored by score

### ISSUE THREAD

**Issue by Bjorn-skytruth** [SkyTruth/kmltrack#2]
@redhog We were unable to get this tool to work. I am interested in coloring a track by score. Its possible it didn't work because there was no course field in the data. The PIPA data we are looking at is below.

pipa_report.PIPA_2012_2013_NOVDEC2014_JANFEB2015

**Comment by geowurster** [comment]
@Bjorn-skytruth can you provide a sample file, command, and error output?  This is pretty ambiguous and doesn't give @redhog anywhere to start.

@redhog I tried to debug but I can't run the unittests as per #1.

**Comment by Bjorn-skytruth** [comment]
Here is the output error. The csv is in flowdock. 

https://www.flowdock.com/rest/files/74661/60m7oCNOgS7LJR2By0OBJg/kmlbyscore.csv

``` console
$ kmltrack kmlbyscore.csv kmlbyscore.kml --format=csv --map-lat="float(latitude)" --map-lon="float(longitude)" --map-color="float(score)"
global name 'cvs' is not defined
```

**Comment by redhog** [comment]
This bug was fixed in the latest dev version, which I've now published to pypi. To upgrade:

```
pip install --upgrade kmltrack
```

You also need to modify your command line slightly (because of another change in the latest version):

```
kmltrack kmlbyscore.csv kmlbyscore.kml --format=csv --map lat="float(latitude)" --map lon="float(longitude)" --map color="float(score)"
```
